// The content of this file was generated by IBM Cloud
// Do not modify it as it might get overridden
const constants = require('./constants');

module.exports = (app) => {
  // catches all next(new Error()) from previous rules, you can set res.status() before you call next(new Error())
  // eslint-disable-next-line
};
